bug25754: Bug in Typing causes ag_connect import to fail in Python 3.5.3
The following fails on a freshly installed agraph-python on python
3.5.3:

from franz.openrdf.connect import ag_connect

with:

TypeError: 'ContextAttribute' object is not callable

The problem code is unused and has been removed.

Tests added for:       no
make test-suite run?   python-prepush
Documentation changes? no

<release-note>
Fixes import of import ag_connect on Python 3.5.3.
</release-note>

Change-Id: I1d9acf022a5ba685c0795ee1684287cc0e237018
Reviewed-on: https://gerrit.franz.com:9080/13129
Reviewed-by: Thomas Hintz <thintz@franz.com>
Tested-by: Hudson <hudson@franz.com>
PTEST: Hudson <hudson@franz.com>
Reviewed-by: Ahmon Dancy <dancy@franz.com>