Removed 3.6 from the list of Python versions to test
The Python that comes from 'conda' changed from 3.6.7 to 3.6.9
recently and we started getting the following failure during tests:

toxenv/bin/tox -e py36-env
py36-env create: /agraph-python/agraph-python/env3
ERROR: invocation failed (exit code 1), logfile: /agraph-python/agraph-python/env3/log/py36-env-0.log
ERROR: actionid: py36-env
msg: getenv
cmdargs: '/agraph-python/agraph-python/toxenv/bin/python3.7 -m virtualenv --python /agraph-python/agraph-python/pythons/3.6/bin/python3.6 env3'

Using base prefix '/agraph-python/agraph-python/pythons/3.6'
New pypy executable in /agraph-python/agraph-python/env3/bin/python3.6
copying /agraph-python/agraph-python/pythons/3.6/bin/python3.6 => /agraph-python/agraph-python/env3/bin/python3.6
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/libpypy3-c.so => /agraph-python/agraph-python/env3/lib/libpypy3-c.so
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/./libbz2.so.1.0 => /agraph-python/agraph-python/env3/lib/libbz2.so.1.0
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/libbz2.so.1.0.8 => /agraph-python/agraph-python/env3/lib/libbz2.so.1.0.8
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/./libexpat.so.1 => /agraph-python/agraph-python/env3/lib/libexpat.so.1
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/libexpat.so.1.6.11 => /agraph-python/agraph-python/env3/lib/libexpat.so.1.6.11
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/./libz.so.1 => /agraph-python/agraph-python/env3/lib/libz.so.1
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/libz.so.1.2.11 => /agraph-python/agraph-python/env3/lib/libz.so.1.2.11
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/./libffi.so.6 => /agraph-python/agraph-python/env3/lib/libffi.so.6
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/libffi.so.6.0.4 => /agraph-python/agraph-python/env3/lib/libffi.so.6.0.4
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/./libncursesw.so.6 => /agraph-python/agraph-python/env3/lib/libncursesw.so.6
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/libncursesw.so.6.1 => /agraph-python/agraph-python/env3/lib/libncursesw.so.6.1
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/./libtinfow.so.6 => /agraph-python/agraph-python/env3/lib/libtinfow.so.6
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/libtinfow.so.6.1 => /agraph-python/agraph-python/env3/lib/libtinfow.so.6.1
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/./libgcc_s.so.1 => /agraph-python/agraph-python/env3/lib/libgcc_s.so.1
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/./libtinfow.so.6 => /agraph-python/agraph-python/env3/lib/libtinfow.so.6
copying /agraph-python/agraph-python/pythons/3.6/bin/../lib/libtinfow.so.6.1 => /agraph-python/agraph-python/env3/lib/libtinfow.so.6.1
Also creating executable in /agraph-python/agraph-python/env3/bin/pypy
Traceback (most recent call last):
  File "/agraph-python/agraph-python/toxenv/lib/python3.7/site-packages/virtualenv.py", line 2884, in <module>
    main()
  File "/agraph-python/agraph-python/toxenv/lib/python3.7/site-packages/virtualenv.py", line 712, in main
    symlink=options.symlink)
  File "/agraph-python/agraph-python/toxenv/lib/python3.7/site-packages/virtualenv.py", line 927, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/agraph-python/agraph-python/toxenv/lib/python3.7/site-packages/virtualenv.py", line 1406, in install_python
    raise e
  File "/agraph-python/agraph-python/toxenv/lib/python3.7/site-packages/virtualenv.py", line 1398, in install_python
    stdout=subprocess.PIPE)
  File "/agraph-python/agraph-python/pythons/3.6/lib-python/3/subprocess.py", line 637, in __init__
    _pypy_install_libs_after_virtualenv(args[0])
  File "/agraph-python/agraph-python/pythons/3.6/lib-python/3/subprocess.py", line 1664, in _pypy_install_libs_after_virtualenv
    shutil.copytree(src_lib, os.path.join(dest_dir, '../lib'))
  File "/agraph-python/agraph-python/pythons/3.6/lib-python/3/shutil.py", line 321, in copytree
    os.makedirs(dst)
  File "/agraph-python/agraph-python/pythons/3.6/lib-python/3/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/agraph-python/agraph-python/env3/bin/../lib'

Change-Id: I97e9c77f7af0e7c24f2563a81aa4c6d8d383760a
Reviewed-on: https://gerrit.franz.com:9080/c/agraph-python/+/15920
Tested-by: Ahmon Dancy <dancy@franz.com>
Reviewed-by: Ahmon Dancy <dancy@franz.com>