Unset PYTHONPATH in the makefile
PYTHONPATH could interfere with the build system and cause unclear
error messages like the one below:

ImportError: This package should not be accessible on Python 3. Either
you are trying to run from the python-future src folder or your
installation of python-future is corrupted.

Change-Id: Ic0a491ad70041bb8e130cbc402dc35fed1d1a095
Reviewed-on: https://gerrit.franz.com:9080/9810
Reviewed-by: Tadeusz Sznuk <ts@franz.com>
Tested-by: Hudson <hudson@franz.com>
Reviewed-by: Hudson <hudson@franz.com>
Reviewed-by: Ahmon Dancy <dancy@franz.com>